# -*- coding: utf-8 -*-
"""Pitcher_Comparison_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wuo7ur1N_WqTr2V9HKsBtJqpH-Hu9eZu
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import math
import numpy as np

pComps = pd.read_csv('2021_pitcher_data.csv')
pCompAvg = pd.DataFrame(pComps)

RHPlist = []
LHPlist = []

for row in pComps.index:
    if (pComps.at[row,'hand'] == 'R'):
        RHPlist.append(pComps.loc[row])
    else:
        LHPlist.append(pComps.loc[row])

RHP = pd.DataFrame(RHPlist)
LHP = pd.DataFrame(LHPlist)

del RHP['player_name']
del LHP['player_name']
del RHP['hand']
del LHP['hand']

RHPaverages = pd.DataFrame(RHP.mean())
LHPaverages = pd.DataFrame(LHP.mean())

for row in pComps.index:
    for column in pComps:
        if (column != 'player_name' and column != 'hand'):
            if (pComps.at[row, 'hand'] == 'R'):
                pCompAvg.at[row, column] = (pComps.at[row, column] - RHPaverages.at[column, 0]) / RHPaverages.at[column, 0]
            else:
                pCompAvg.at[row, column] = (pComps.at[row, column] - LHPaverages.at[column, 0]) / LHPaverages.at[column, 0]

chosenPlayerLoc = -1

# While loop will prompt the user for a player name until the user enters a player name that is recognized in the data set
while (chosenPlayerLoc == -1):
    userPlayer = input('Enter an MLB pitcher''s name in the "Lastname, Firstname" format: ')
    for row in pComps.index:
        if (pComps.at[row, 'player_name'] == userPlayer):
            chosenPlayerLoc = row
            break
    if (chosenPlayerLoc == -1):
        print('Invalid entry.')

# Find selected player's difference from average in all applicable stats (example of non-applicable stat would be average cutter velocity if the player does not throw a cutter)

eligiblePlayerCompsList = []
for row in pComps.index:
    if ((pComps.at[row,'hand'] == pComps.at[chosenPlayerLoc,'hand']) and (pComps.at[row, 'player_name'] != pComps.at[chosenPlayerLoc, 'player_name'])):
        eligiblePlayerCompsList.append(pComps.loc[row])

eligiblePlayerComps = pd.DataFrame(eligiblePlayerCompsList)

for row in eligiblePlayerComps.index:
    eligiblePlayerComps.loc[row,'ff_speed':'fs_RPz'] = abs(pComps.loc[chosenPlayerLoc,'ff_speed':'fs_RPz'] - eligiblePlayerComps.loc[row,'ff_speed':'fs_RPz'])

eligiblePlayerComps['ffComps'] = np.nan
eligiblePlayerComps['slComps'] = np.nan
eligiblePlayerComps['chComps'] = np.nan
eligiblePlayerComps['cuComps'] = np.nan
eligiblePlayerComps['siComps'] = np.nan
eligiblePlayerComps['fcComps'] = np.nan
eligiblePlayerComps['fsComps'] = np.nan

for row in eligiblePlayerComps.index:
    if (np.isnan(eligiblePlayerComps.at[row, 'ff_speed']) == False):
        if ((np.isnan(eligiblePlayerComps.at[row, 'ff_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'ff_RPz']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False)):
            eligiblePlayerComps.at[row, 'ffComps'] = 7
        elif ((np.isnan(eligiblePlayerComps.at[row, 'ff_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'ff_RPz']) == False)):
            eligiblePlayerComps.at[row, 'ffComps'] = 6
        elif (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False):
            eligiblePlayerComps.at[row, 'ffComps'] = 5
        else:
            eligiblePlayerComps.at[row, 'ffComps'] = 4
    if (np.isnan(eligiblePlayerComps.at[row, 'sl_speed']) == False):
        if ((np.isnan(eligiblePlayerComps.at[row, 'sl_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'sl_RPz']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False)):
            eligiblePlayerComps.at[row, 'slComps'] = 7
        elif ((np.isnan(eligiblePlayerComps.at[row, 'sl_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'sl_RPz']) == False)):
            eligiblePlayerComps.at[row, 'slComps'] = 6
        elif (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False):
            eligiblePlayerComps.at[row, 'slComps'] = 5
        else:
            eligiblePlayerComps.at[row, 'slComps'] = 4
    if (np.isnan(eligiblePlayerComps.at[row, 'ch_speed']) == False):
        if ((np.isnan(eligiblePlayerComps.at[row, 'ch_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'ch_RPz']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False)):
            eligiblePlayerComps.at[row, 'chComps'] = 7
        elif ((np.isnan(eligiblePlayerComps.at[row, 'ch_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'ch_RPz']) == False)):
            eligiblePlayerComps.at[row, 'chComps'] = 6
        elif (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False):
            eligiblePlayerComps.at[row, 'chComps'] = 5
        else:
            eligiblePlayerComps.at[row, 'cuComps'] = 4
    if (np.isnan(eligiblePlayerComps.at[row, 'cu_speed']) == False):
        if ((np.isnan(eligiblePlayerComps.at[row, 'cu_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'cu_RPz']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False)):
            eligiblePlayerComps.at[row, 'cuComps'] = 7
        elif ((np.isnan(eligiblePlayerComps.at[row, 'cu_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'cu_RPz']) == False)):
            eligiblePlayerComps.at[row, 'cuComps'] = 6
        elif (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False):
            eligiblePlayerComps.at[row, 'cuComps'] = 5
        else:
            eligiblePlayerComps.at[row, 'cuComps'] = 4
    if (np.isnan(eligiblePlayerComps.at[row, 'si_speed']) == False):
        if ((np.isnan(eligiblePlayerComps.at[row, 'si_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'si_RPz']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False)):
            eligiblePlayerComps.at[row, 'siComps'] = 7
        elif ((np.isnan(eligiblePlayerComps.at[row, 'si_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'si_RPz']) == False)):
            eligiblePlayerComps.at[row, 'siComps'] = 6
        elif (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False):
            eligiblePlayerComps.at[row, 'siComps'] = 5
        else:
            eligiblePlayerComps.at[row, 'siComps'] = 4
    if (np.isnan(eligiblePlayerComps.at[row, 'fc_speed']) == False):
        if ((np.isnan(eligiblePlayerComps.at[row, 'fc_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'fc_RPz']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False)):
            eligiblePlayerComps.at[row, 'fcComps'] = 7
        elif ((np.isnan(eligiblePlayerComps.at[row, 'fc_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'fc_RPz']) == False)):
            eligiblePlayerComps.at[row, 'fcComps'] = 6
        elif (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False):
            eligiblePlayerComps.at[row, 'fcComps'] = 5
        else:
            eligiblePlayerComps.at[row, 'fcComps'] = 4
    if (np.isnan(eligiblePlayerComps.at[row, 'fs_speed']) == False):
        if ((np.isnan(eligiblePlayerComps.at[row, 'fs_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'fs_RPz']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False)):
            eligiblePlayerComps.at[row, 'fsComps'] = 7
        elif ((np.isnan(eligiblePlayerComps.at[row, 'fs_RPx']) == False) and (np.isnan(eligiblePlayerComps.at[row, 'fs_RPz']) == False)):
            eligiblePlayerComps.at[row, 'fsComps'] = 6
        elif (np.isnan(eligiblePlayerComps.at[row, 'release_extension']) == False):
            eligiblePlayerComps.at[row, 'fsComps'] = 5
        else:
            eligiblePlayerComps.at[row, 'fsComps'] = 4

nameData = []
ffScoreData = []
slScoreData = []
chScoreData = []
cuScoreData = []
siScoreData = []
fcScoreData = []
fsScoreData = []

for row in eligiblePlayerComps.index:
    nameData.append(eligiblePlayerComps.at[row, 'player_name'])
    ffScoreData.append(np.nan)
    slScoreData.append(np.nan)
    chScoreData.append(np.nan)
    cuScoreData.append(np.nan)
    siScoreData.append(np.nan)
    fcScoreData.append(np.nan)
    fsScoreData.append(np.nan)

differenceScores = pd.DataFrame(list(zip(nameData, ffScoreData, slScoreData, chScoreData, cuScoreData, siScoreData, fcScoreData, fsScoreData)), 
                                columns = ['player_name', 'ff_score', 'sl_score', 'ch_score', 'cu_score', 'si_score', 'fc_score', 'fs_score'])

difScoreRow = 0

for row in eligiblePlayerComps.index:
    if (eligiblePlayerComps.at[row, 'ffComps'] == 7):
        differenceScores.at[difScoreRow, 'ff_score'] = (eligiblePlayerComps.at[row, 'ff_speed'] + eligiblePlayerComps.at[row, 'ff_spin'] + eligiblePlayerComps.at[row, 'ff_xBreak'] + eligiblePlayerComps.at[row, 'ff_zBreak'] + eligiblePlayerComps.at[row, 'ff_RPx'] + eligiblePlayerComps.at[row, 'ff_RPz'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'ffComps']
    elif (eligiblePlayerComps.at[row, 'ffComps'] == 6):
        differenceScores.at[difScoreRow, 'ff_score'] = (eligiblePlayerComps.at[row, 'ff_speed'] + eligiblePlayerComps.at[row, 'ff_spin'] + eligiblePlayerComps.at[row, 'ff_xBreak'] + eligiblePlayerComps.at[row, 'ff_zBreak'] + eligiblePlayerComps.at[row, 'ff_RPx'] + eligiblePlayerComps.at[row, 'ff_RPz']) / eligiblePlayerComps.at[row, 'ffComps']
    elif (eligiblePlayerComps.at[row, 'ffComps'] == 5):
        differenceScores.at[difScoreRow, 'ff_score'] = (eligiblePlayerComps.at[row, 'ff_speed'] + eligiblePlayerComps.at[row, 'ff_spin'] + eligiblePlayerComps.at[row, 'ff_xBreak'] + eligiblePlayerComps.at[row, 'ff_zBreak'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'ffComps']
    elif (eligiblePlayerComps.at[row, 'ffComps'] == 4):
        differenceScores.at[difScoreRow, 'ff_score'] = (eligiblePlayerComps.at[row, 'ff_speed'] + eligiblePlayerComps.at[row, 'ff_spin'] + eligiblePlayerComps.at[row, 'ff_xBreak'] + eligiblePlayerComps.at[row, 'ff_zBreak']) / eligiblePlayerComps.at[row, 'ffComps']
    
    if (eligiblePlayerComps.at[row, 'slComps'] == 7):
        differenceScores.at[difScoreRow, 'sl_score'] = (eligiblePlayerComps.at[row, 'sl_speed'] + eligiblePlayerComps.at[row, 'sl_spin'] + eligiblePlayerComps.at[row, 'sl_xBreak'] + eligiblePlayerComps.at[row, 'sl_zBreak'] + eligiblePlayerComps.at[row, 'sl_RPx'] + eligiblePlayerComps.at[row, 'sl_RPz'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'slComps']
    elif (eligiblePlayerComps.at[row, 'slComps'] == 6):
        differenceScores.at[difScoreRow, 'sl_score'] = (eligiblePlayerComps.at[row, 'sl_speed'] + eligiblePlayerComps.at[row, 'sl_spin'] + eligiblePlayerComps.at[row, 'sl_xBreak'] + eligiblePlayerComps.at[row, 'sl_zBreak'] + eligiblePlayerComps.at[row, 'sl_RPx'] + eligiblePlayerComps.at[row, 'sl_RPz']) / eligiblePlayerComps.at[row, 'slComps']
    elif (eligiblePlayerComps.at[row, 'slComps'] == 5):
        differenceScores.at[difScoreRow, 'sl_score'] = (eligiblePlayerComps.at[row, 'sl_speed'] + eligiblePlayerComps.at[row, 'sl_spin'] + eligiblePlayerComps.at[row, 'sl_xBreak'] + eligiblePlayerComps.at[row, 'sl_zBreak'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'slComps']
    elif (eligiblePlayerComps.at[row, 'slComps'] == 4):
        differenceScores.at[difScoreRow, 'sl_score'] = (eligiblePlayerComps.at[row, 'sl_speed'] + eligiblePlayerComps.at[row, 'sl_spin'] + eligiblePlayerComps.at[row, 'sl_xBreak'] + eligiblePlayerComps.at[row, 'sl_zBreak']) / eligiblePlayerComps.at[row, 'slComps']
    
    if (eligiblePlayerComps.at[row, 'chComps'] == 7):
        differenceScores.at[difScoreRow, 'ch_score'] = (eligiblePlayerComps.at[row, 'ch_speed'] + eligiblePlayerComps.at[row, 'ch_spin'] + eligiblePlayerComps.at[row, 'ch_xBreak'] + eligiblePlayerComps.at[row, 'ch_zBreak'] + eligiblePlayerComps.at[row, 'ch_RPx'] + eligiblePlayerComps.at[row, 'ch_RPz'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'chComps']
    elif (eligiblePlayerComps.at[row, 'chComps'] == 6):
        differenceScores.at[difScoreRow, 'ch_score'] = (eligiblePlayerComps.at[row, 'ch_speed'] + eligiblePlayerComps.at[row, 'ch_spin'] + eligiblePlayerComps.at[row, 'ch_xBreak'] + eligiblePlayerComps.at[row, 'ch_zBreak'] + eligiblePlayerComps.at[row, 'ch_RPx'] + eligiblePlayerComps.at[row, 'ch_RPz']) / eligiblePlayerComps.at[row, 'chComps']
    elif (eligiblePlayerComps.at[row, 'chComps'] == 5):
        differenceScores.at[difScoreRow, 'ch_score'] = (eligiblePlayerComps.at[row, 'ch_speed'] + eligiblePlayerComps.at[row, 'ch_spin'] + eligiblePlayerComps.at[row, 'ch_xBreak'] + eligiblePlayerComps.at[row, 'ch_zBreak'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'chComps']
    elif (eligiblePlayerComps.at[row, 'chComps'] == 4):
        differenceScores.at[difScoreRow, 'ch_score'] = (eligiblePlayerComps.at[row, 'ch_speed'] + eligiblePlayerComps.at[row, 'ch_spin'] + eligiblePlayerComps.at[row, 'ch_xBreak'] + eligiblePlayerComps.at[row, 'ch_zBreak']) / eligiblePlayerComps.at[row, 'chComps']
    
    if (eligiblePlayerComps.at[row, 'cuComps'] == 7):
        differenceScores.at[difScoreRow, 'cu_score'] = (eligiblePlayerComps.at[row, 'cu_speed'] + eligiblePlayerComps.at[row, 'cu_spin'] + eligiblePlayerComps.at[row, 'cu_xBreak'] + eligiblePlayerComps.at[row, 'cu_zBreak'] + eligiblePlayerComps.at[row, 'cu_RPx'] + eligiblePlayerComps.at[row, 'cu_RPz'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'cuComps']
    elif (eligiblePlayerComps.at[row, 'cuComps'] == 6):
        differenceScores.at[difScoreRow, 'cu_score'] = (eligiblePlayerComps.at[row, 'cu_speed'] + eligiblePlayerComps.at[row, 'cu_spin'] + eligiblePlayerComps.at[row, 'cu_xBreak'] + eligiblePlayerComps.at[row, 'cu_zBreak'] + eligiblePlayerComps.at[row, 'cu_RPx'] + eligiblePlayerComps.at[row, 'cu_RPz']) / eligiblePlayerComps.at[row, 'cuComps']
    elif (eligiblePlayerComps.at[row, 'cuComps'] == 5):
        differenceScores.at[difScoreRow, 'cu_score'] = (eligiblePlayerComps.at[row, 'cu_speed'] + eligiblePlayerComps.at[row, 'cu_spin'] + eligiblePlayerComps.at[row, 'cu_xBreak'] + eligiblePlayerComps.at[row, 'cu_zBreak'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'cuComps']
    elif (eligiblePlayerComps.at[row, 'cuComps'] == 4):
        differenceScores.at[difScoreRow, 'cu_score'] = (eligiblePlayerComps.at[row, 'cu_speed'] + eligiblePlayerComps.at[row, 'cu_spin'] + eligiblePlayerComps.at[row, 'cu_xBreak'] + eligiblePlayerComps.at[row, 'cu_zBreak']) / eligiblePlayerComps.at[row, 'cuComps']
    
    if (eligiblePlayerComps.at[row, 'siComps'] == 7):
        differenceScores.at[difScoreRow, 'si_score'] = (eligiblePlayerComps.at[row, 'si_speed'] + eligiblePlayerComps.at[row, 'si_spin'] + eligiblePlayerComps.at[row, 'si_xBreak'] + eligiblePlayerComps.at[row, 'si_zBreak'] + eligiblePlayerComps.at[row, 'si_RPx'] + eligiblePlayerComps.at[row, 'si_RPz'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'siComps']
    elif (eligiblePlayerComps.at[row, 'siComps'] == 6):
        differenceScores.at[difScoreRow, 'si_score'] = (eligiblePlayerComps.at[row, 'si_speed'] + eligiblePlayerComps.at[row, 'si_spin'] + eligiblePlayerComps.at[row, 'si_xBreak'] + eligiblePlayerComps.at[row, 'si_zBreak'] + eligiblePlayerComps.at[row, 'si_RPx'] + eligiblePlayerComps.at[row, 'si_RPz']) / eligiblePlayerComps.at[row, 'siComps']
    elif (eligiblePlayerComps.at[row, 'siComps'] == 5):
        differenceScores.at[difScoreRow, 'si_score'] = (eligiblePlayerComps.at[row, 'si_speed'] + eligiblePlayerComps.at[row, 'si_spin'] + eligiblePlayerComps.at[row, 'si_xBreak'] + eligiblePlayerComps.at[row, 'si_zBreak'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'siComps']
    elif (eligiblePlayerComps.at[row, 'siComps'] == 4):
        differenceScores.at[difScoreRow, 'si_score'] = (eligiblePlayerComps.at[row, 'si_speed'] + eligiblePlayerComps.at[row, 'si_spin'] + eligiblePlayerComps.at[row, 'si_xBreak'] + eligiblePlayerComps.at[row, 'si_zBreak']) / eligiblePlayerComps.at[row, 'siComps']
    
    if (eligiblePlayerComps.at[row, 'fcComps'] == 7):
        differenceScores.at[difScoreRow, 'fc_score'] = (eligiblePlayerComps.at[row, 'fc_speed'] + eligiblePlayerComps.at[row, 'fc_spin'] + eligiblePlayerComps.at[row, 'fc_xBreak'] + eligiblePlayerComps.at[row, 'fc_zBreak'] + eligiblePlayerComps.at[row, 'fc_RPx'] + eligiblePlayerComps.at[row, 'fc_RPz'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'fcComps']
    elif (eligiblePlayerComps.at[row, 'fcComps'] == 6):
        differenceScores.at[difScoreRow, 'fc_score'] = (eligiblePlayerComps.at[row, 'fc_speed'] + eligiblePlayerComps.at[row, 'fc_spin'] + eligiblePlayerComps.at[row, 'fc_xBreak'] + eligiblePlayerComps.at[row, 'fc_zBreak'] + eligiblePlayerComps.at[row, 'fc_RPx'] + eligiblePlayerComps.at[row, 'fc_RPz']) / eligiblePlayerComps.at[row, 'fcComps']
    elif (eligiblePlayerComps.at[row, 'fcComps'] == 5):
        differenceScores.at[difScoreRow, 'fc_score'] = (eligiblePlayerComps.at[row, 'fc_speed'] + eligiblePlayerComps.at[row, 'fc_spin'] + eligiblePlayerComps.at[row, 'fc_xBreak'] + eligiblePlayerComps.at[row, 'fc_zBreak'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'fcComps']
    elif (eligiblePlayerComps.at[row, 'fcComps'] == 4):
        differenceScores.at[difScoreRow, 'fc_score'] = (eligiblePlayerComps.at[row, 'fc_speed'] + eligiblePlayerComps.at[row, 'fc_spin'] + eligiblePlayerComps.at[row, 'fc_xBreak'] + eligiblePlayerComps.at[row, 'fc_zBreak']) / eligiblePlayerComps.at[row, 'fcComps']
    
    if (eligiblePlayerComps.at[row, 'fsComps'] == 7):
        differenceScores.at[difScoreRow, 'fs_score'] = (eligiblePlayerComps.at[row, 'fs_speed'] + eligiblePlayerComps.at[row, 'fs_spin'] + eligiblePlayerComps.at[row, 'fs_xBreak'] + eligiblePlayerComps.at[row, 'fs_zBreak'] + eligiblePlayerComps.at[row, 'fs_RPx'] + eligiblePlayerComps.at[row, 'fs_RPz'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'fsComps']
    elif (eligiblePlayerComps.at[row, 'fsComps'] == 6):
        differenceScores.at[difScoreRow, 'fs_score'] = (eligiblePlayerComps.at[row, 'fs_speed'] + eligiblePlayerComps.at[row, 'fs_spin'] + eligiblePlayerComps.at[row, 'fs_xBreak'] + eligiblePlayerComps.at[row, 'fs_zBreak'] + eligiblePlayerComps.at[row, 'fs_RPx'] + eligiblePlayerComps.at[row, 'fs_RPz']) / eligiblePlayerComps.at[row, 'fsComps']
    elif (eligiblePlayerComps.at[row, 'fsComps'] == 5):
        differenceScores.at[difScoreRow, 'fs_score'] = (eligiblePlayerComps.at[row, 'fs_speed'] + eligiblePlayerComps.at[row, 'fs_spin'] + eligiblePlayerComps.at[row, 'fs_xBreak'] + eligiblePlayerComps.at[row, 'fs_zBreak'] + eligiblePlayerComps.at[row, 'release_extension']) / eligiblePlayerComps.at[row, 'fsComps']
    elif (eligiblePlayerComps.at[row, 'fsComps'] == 4):
        differenceScores.at[difScoreRow, 'fs_score'] = (eligiblePlayerComps.at[row, 'fs_speed'] + eligiblePlayerComps.at[row, 'fs_spin'] + eligiblePlayerComps.at[row, 'fs_xBreak'] + eligiblePlayerComps.at[row, 'fs_zBreak']) / eligiblePlayerComps.at[row, 'fsComps']
    
    difScoreRow += 1

nComps = 3

print(pComps.at[chosenPlayerLoc, 'player_name'], 'Pitch Repetoire:')
if (np.isnan(pComps.at[chosenPlayerLoc, 'ff_speed']) == False):
    print('Four Seam Fastball')
    print('   Most similar pitches:')
    differenceScores.sort_values('ff_score', inplace = True)
    differenceScores.reset_index(drop = True, inplace = True)
    for i in range(nComps):
        print('    ', differenceScores.at[i, 'player_name'], '-- Difference Score:', round(differenceScores.at[i, 'ff_score'], 3))
if (np.isnan(pComps.at[chosenPlayerLoc, 'fc_speed']) == False):
    print('Cutter')
    print('   Most similar pitches:')
    differenceScores.sort_values('cu_score', inplace = True)
    differenceScores.reset_index(drop = True, inplace = True)
    for i in range(nComps):
        print('    ', differenceScores.at[i, 'player_name'], '-- Difference Score:', round(differenceScores.at[i, 'cu_score'], 3))
if (np.isnan(pComps.at[chosenPlayerLoc, 'si_speed']) == False):
    print('Sinker')
    print('   Most similar pitches:')
    differenceScores.sort_values('si_score', inplace = True)
    differenceScores.reset_index(drop = True, inplace = True)
    for i in range(nComps):
        print('    ', differenceScores.at[i, 'player_name'], '-- Difference Score:', round(differenceScores.at[i, 'si_score'], 3))
if (np.isnan(pComps.at[chosenPlayerLoc, 'fs_speed']) == False):
    print('Splitter')
    print('   Most similar pitches:')
    differenceScores.sort_values('fs_score', inplace = True)
    differenceScores.reset_index(drop = True, inplace = True)
    for i in range(nComps):
        print('    ', differenceScores.at[i, 'player_name'], '-- Difference Score:', round(differenceScores.at[i, 'fs_score'], 3))
if (np.isnan(pComps.at[chosenPlayerLoc, 'sl_speed']) == False):
    print('Slider')
    print('   Most similar pitches:')
    differenceScores.sort_values('sl_score', inplace = True)
    differenceScores.reset_index(drop = True, inplace = True)
    for i in range(nComps):
        print('    ', differenceScores.at[i, 'player_name'], '-- Difference Score:', round(differenceScores.at[i, 'sl_score'], 3))
if (np.isnan(pComps.at[chosenPlayerLoc, 'cu_speed']) == False):
    print('Curveball')
    print('   Most similar pitches:')
    differenceScores.sort_values('cu_score', inplace = True)
    differenceScores.reset_index(drop = True, inplace = True)
    for i in range(nComps):
        print('    ', differenceScores.at[i, 'player_name'], '-- Difference Score:', round(differenceScores.at[i, 'cu_score'], 3))
if (np.isnan(pComps.at[chosenPlayerLoc, 'ch_speed']) == False):
    print('Changeup')
    print('   Most similar pitches:')
    differenceScores.sort_values('ch_score', inplace = True)
    differenceScores.reset_index(drop = True, inplace = True)
    for i in range(nComps):
        print('    ', differenceScores.at[i, 'player_name'], '-- Difference Score:', round(differenceScores.at[i, 'ch_score'], 3))